//! Reading Truth Social status captures out of CDX index files.
//!
//! [`read_all`] streams every CDX entry in a directory (via [`truthsocial_wbm::cdx`]) and reduces
//! each status capture to a compact [`Row`] of `(id, timestamp, digest)`, sorted and deduplicated.
//! [`read_compressed_csv`] reads the zstd-compressed CSV that the `extract` command emits back into
//! the same rows.

use archivindex_wbm::{cdx::item::Item, digest::Sha1Digest, timestamp::Timestamp};
use cli_helpers::prelude::log;
use regex::Regex;
use std::fs::File;
use std::io::BufReader;
use std::path::{Path, PathBuf};
use std::sync::LazyLock;
use thiserror::Error;
use truthsocial_wbm::cdx::{CdxError, read_cdx_entries};

/// Captures the numeric status ID in an `/api/v1/statuses/{id}` Truth Social API URL.
static STATUS_ID_REGEX: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"https://truthsocial.com/api/v1/statuses/(\d+)").expect("invalid status ID regex")
});

/// An error reading CDX captures.
#[derive(Debug, Error)]
pub enum Error {
    #[error("I/O error")]
    Io(#[from] std::io::Error),
    #[error("File I/O error")]
    FileIo {
        error: std::io::Error,
        path: PathBuf,
    },

    /// A CDX entry file could not be read or parsed.
    #[error("CDX directory reading error")]
    Cdx(#[from] CdxError),

    /// The original URL does not contain a recognizable status ID pattern.
    #[error("failed to parse status ID from URL: {0}")]
    InvalidStatusId(String),

    /// The extracted status ID string could not be parsed as a `u64`.
    #[error("status ID is not a valid u64: {0}")]
    ParseIntError(#[from] std::num::ParseIntError),

    /// The digest in the CDX item is not a valid SHA-1 digest.
    #[error("invalid digest: {0}")]
    InvalidDigest(String),

    /// Error reading CSV data.
    #[error("CSV error")]
    Csv(#[from] csv::Error),

    /// A timestamp field could not be parsed as a Wayback-format timestamp.
    #[error("invalid timestamp: {0}")]
    InvalidTimestamp(String),
}

/// Reads every CDX entry file in `base`, reduces each Truth Social status capture to a [`Row`], and
/// returns the rows sorted by `(id, timestamp, digest)` with exact duplicates removed.
///
/// The directory is read through [`truthsocial_wbm::cdx::read_cdx_entries`], which streams both
/// plain (`*.json`) and zstd-compressed (`*.json.zst`) files. Entries whose URL is not a status
/// (e.g. account or media captures) or whose digest is invalid are logged and skipped rather than
/// aborting the run.
///
/// # Errors
///
/// Returns [`Error::Cdx`] if the directory cannot be opened or one of its files cannot be read or
/// parsed.
pub fn read_all<P: AsRef<Path>>(base: P) -> Result<Vec<Row>, Error> {
    let mut rows = Vec::new();

    for entry in read_cdx_entries(base)? {
        let item = entry?;
        match Row::try_from(&item) {
            Ok(row) => rows.push(row),
            // Non-status captures and invalid digests are expected in a raw CDX directory; skip
            // them so a few stray entries do not abort the whole extraction.
            Err(error) => log::warn!("Skipping CDX item {}: {error}", item.original),
        }
    }

    log::info!("Sorting and deduplicating {} rows", rows.len());
    rows.sort_unstable();
    rows.dedup();

    Ok(rows)
}

/// Reads rows from a zstd-compressed CSV file generated by the `extract` command.
///
/// Each row has three columns: the status URL, the capture timestamp in Wayback Machine format
/// (`YYYYMMDDHHmmss`), and the Base32 SHA-1 content digest.
///
/// # Errors
///
/// Returns an error if the file cannot be opened, zstd decompression or CSV parsing fails, or a row
/// contains an invalid URL, timestamp, or digest.
pub fn read_compressed_csv<P: AsRef<Path>>(path: P) -> Result<Vec<Row>, Error> {
    let path = path.as_ref();
    let file = File::open(path).map_err(|error| Error::FileIo {
        error,
        path: path.to_path_buf(),
    })?;

    // Wrap the file in a zstd decoder, then buffer it for efficient reading. The `zstd::Decoder`
    // streams decompression as the CSV reader pulls data.
    let decoder = zstd::Decoder::new(file).map_err(|error| Error::FileIo {
        error,
        path: path.to_path_buf(),
    })?;
    let reader = BufReader::new(decoder);

    // `extract` writes raw data rows with no header.
    let mut csv_reader = csv::ReaderBuilder::new()
        .has_headers(false)
        .from_reader(reader);

    let mut rows = Vec::new();

    for result in csv_reader.records() {
        let record = result?;

        let url = record
            .get(0)
            .ok_or_else(|| Error::InvalidStatusId("missing URL field".to_string()))?;
        let id = parse_status_id(url)?;

        // `Timestamp` implements `FromStr` for the fourteen-digit Wayback format.
        let timestamp_str = record
            .get(1)
            .ok_or_else(|| Error::InvalidTimestamp("missing timestamp field".to_string()))?;
        let timestamp: Timestamp = timestamp_str
            .parse()
            .map_err(|_| Error::InvalidTimestamp(timestamp_str.to_string()))?;

        // `Sha1Digest` implements `FromStr` to decode the Base32 digest.
        let digest_str = record
            .get(2)
            .ok_or_else(|| Error::InvalidDigest("missing digest field".to_string()))?;
        let digest: Sha1Digest = digest_str
            .parse()
            .map_err(|_| Error::InvalidDigest(digest_str.to_string()))?;

        rows.push(Row {
            id,
            timestamp,
            digest,
        });
    }

    Ok(rows)
}

/// Extracts the status ID from a Truth Social API URL.
///
/// # Errors
///
/// [`Error::InvalidStatusId`] if the URL has no `/api/v1/statuses/{id}` segment, or
/// [`Error::ParseIntError`] if the captured id does not fit in a `u64`.
pub fn parse_status_id(url: &str) -> Result<u64, Error> {
    let captures = STATUS_ID_REGEX
        .captures(url)
        .ok_or_else(|| Error::InvalidStatusId(url.to_string()))?;

    let id_str = captures
        .get(1)
        .ok_or_else(|| Error::InvalidStatusId(url.to_string()))?
        .as_str();

    Ok(id_str.parse()?)
}

/// A Truth Social status capture reduced to its identity: the status ID, capture timestamp, and
/// content digest.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub struct Row {
    pub id: u64,
    pub timestamp: Timestamp,
    pub digest: Sha1Digest,
}

impl TryFrom<&Item<'_>> for Row {
    type Error = Error;

    fn try_from(value: &Item<'_>) -> Result<Self, Self::Error> {
        let id = parse_status_id(value.original.as_ref())?;

        // `Digest` is `Valid(Sha1Digest) | Invalid(Cow<str>)`; reject captures with an invalid one.
        let digest = value
            .digest
            .map_err(|invalid| Error::InvalidDigest(invalid.to_string()))?;

        Ok(Self {
            id,
            timestamp: value.timestamp,
            digest,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use archivindex_wbm::cdx::item::ItemList;

    /// The regex extracts the numeric id from a well-formed status URL.
    #[test]
    fn status_id_regex_matches_status_url() {
        let url = "https://truthsocial.com/api/v1/statuses/107867707128487959";
        let captures = STATUS_ID_REGEX.captures(url).expect("regex should match");
        let id_str = captures.get(1).expect("capture group").as_str();
        assert_eq!(id_str, "107867707128487959");
    }

    /// The regex matches status ids of any length.
    #[test]
    fn status_id_regex_matches_various_lengths() {
        let cases = [
            ("https://truthsocial.com/api/v1/statuses/1", "1"),
            (
                "https://truthsocial.com/api/v1/statuses/123456789",
                "123456789",
            ),
            (
                "https://truthsocial.com/api/v1/statuses/999999999999999999",
                "999999999999999999",
            ),
        ];

        for (url, expected) in cases {
            let captures = STATUS_ID_REGEX
                .captures(url)
                .unwrap_or_else(|| panic!("should match: {url}"));
            assert_eq!(captures.get(1).unwrap().as_str(), expected);
        }
    }

    /// The regex rejects non-status URLs (profiles, account endpoints, other hosts).
    #[test]
    fn status_id_regex_rejects_non_status_urls() {
        let urls = [
            "https://truthsocial.com/@username/107867707128487959",
            "https://truthsocial.com/users/username/statuses/107867707128487959",
            "https://truthsocial.com/api/v1/accounts/123456",
            "https://example.com/api/v1/statuses/123456",
            "not a url at all",
        ];

        for url in urls {
            assert!(
                STATUS_ID_REGEX.captures(url).is_none(),
                "should not match: {url}"
            );
        }
    }

    /// A non-status URL yields [`Error::InvalidStatusId`] when converted to a [`Row`].
    #[test]
    fn row_try_from_rejects_non_status_url() {
        let cdx = r#"[
            ["urlkey","timestamp","original","mimetype","statuscode","digest","length"],
            ["com,truthsocial)/@username/12345","20220227025629","https://truthsocial.com/@username/12345","application/json","200","ZHYT52YPEOCHJD5FZINSDYXGQZI22WJ4","1234"]
        ]"#;

        let items: ItemList = serde_json::from_str(cdx).expect("parse CDX");
        assert_eq!(items.values.len(), 1);

        match Row::try_from(&items.values[0]) {
            Err(Error::InvalidStatusId(url)) => assert!(url.contains("@username")),
            other => panic!("expected InvalidStatusId, got {other:?}"),
        }
    }

    /// A valid status capture converts to a [`Row`] carrying its id, timestamp, and digest.
    #[test]
    fn row_try_from_reads_status_capture() {
        let cdx = r#"[
            ["urlkey","timestamp","original","mimetype","statuscode","digest","length"],
            ["com,truthsocial)/api/v1/statuses/107867707128487959","20220227025629","https://truthsocial.com/api/v1/statuses/107867707128487959","application/json","200","ZHYT52YPEOCHJD5FZINSDYXGQZI22WJ4","1234"]
        ]"#;

        let items: ItemList = serde_json::from_str(cdx).expect("parse CDX");
        let row = Row::try_from(&items.values[0]).expect("convert");

        assert_eq!(row.id, 107867707128487959);
        // `Timestamp` renders back to the fourteen-digit Wayback format it was parsed from.
        assert_eq!(row.timestamp.to_string(), "20220227025629");
    }

    /// Rows order by `(id, timestamp, digest)`.
    #[test]
    fn row_orders_by_id_then_timestamp() {
        let cdx = r#"[
            ["urlkey","timestamp","original","mimetype","statuscode","digest","length"],
            ["com,truthsocial)/api/v1/statuses/100","20220227025629","https://truthsocial.com/api/v1/statuses/100","application/json","200","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2","1234"],
            ["com,truthsocial)/api/v1/statuses/200","20220227025629","https://truthsocial.com/api/v1/statuses/200","application/json","200","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2","1234"],
            ["com,truthsocial)/api/v1/statuses/100","20220228025629","https://truthsocial.com/api/v1/statuses/100","application/json","200","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2","1234"]
        ]"#;

        let items: ItemList = serde_json::from_str(cdx).expect("parse CDX");
        let mut rows = items
            .values
            .iter()
            .map(|item| Row::try_from(item).unwrap())
            .collect::<Vec<_>>();
        rows.sort_unstable();

        assert_eq!(rows[0].id, 100);
        assert_eq!(rows[0].timestamp.to_string(), "20220227025629");
        assert_eq!(rows[1].id, 100);
        assert_eq!(rows[1].timestamp.to_string(), "20220228025629");
        assert_eq!(rows[2].id, 200);
    }
}
